from __future__ import annotations

# Fixed Dimensions
# Cryostat dimensions
CRYOSTAT_HEIGHT = 171.0
CRYOSTAT_WIDTH = 101.6
CRYOSTAT_THICKNESS = 1.5
POSITION_CRYOSTAT_CAVITY_FROM_TOP = 1.5
POSITION_CRYOSTAT_CAVITY_FROM_BOTTOM = 0.8
POSITION_CRYOSTAT_FROM_BOTTOM = 250.0
# Base dimensions
BASE_WIDTH = 480.0
BASE_DEPTH = 450.0
BASE_HEIGHT = 500.0
# Inner cavity dimensions
INNER_CAVITY_WIDTH = 300.0
INNER_CAVITY_DEPTH = 250.0
INNER_CAVITY__HEIGHT = 500.0
# Cavity dimensions
CAVITY_WIDTH = 120.0
CAVITY_DEPTH = 100.0
CAVITY_HEIGHT = 400.0
# Top dimensions
TOP_WIDTH = 300.0
TOP_DEPTH = 300.0
TOP_HEIGHT = 90.0
# Front dimensions
FRONT_WIDTH = 160.0
FRONT_DEPTH = 100.0
FRONT_HEIGTH = 400.0
# Bottom plate
BOTTOM_PLATE_WIDTH = 750.0
BOTTOM_PLATE_DEPTH = 750.0
BOTTOM_PLATE_HEIGHT = 15.0
# Cavity bottom plate
CAVITY_BOTTOM_PLATE_WIDHT = 120.0
CAVITY_BOTTOM_PLATE_DEPTH = 940.0
CAVITY_BOTTOM_PLATE_HEIGHT = 20.0
# Source holder dimensions
SOURCE_HOLDER_TOP_PLATE_HEIGHT = 3.0
SOURCE_HOLDER_TOP_PLATE_WIDTH = 30.0
SOURCE_HOLDER_TOP_HEIGHT = 10.0
SOURCE_HOLDER_TOP_INNER_WIDTH = 20.0
SOURCE_HOLDER_INNER_WIDTH = 87.0
SOURCE_HOLDER_BOTTOM_INNER_WIDTH = 102.0
SOURCE_HOLDER_OUTER_WIDTH = 108.0
SOURCE_HOLDER_TOPBOTTOM_HEIGHT = 6.1
# Source dimensions
SOURCE_HEIGHT = 0.1
SOURCE_WIDTH = 5.0
# Source foil
SOURCE_FOIL_HEIGHT = 0.5
SOURCE_FOIL_WIDTH = 26.0
# Aluminum ring around source
SOURCE_AL_RING_HEIGHT = 3.0
SOURCE_AL_RING_WIDTH_MAX = 30.0
SOURCE_AL_RING_WIDTH_MIN = 26.0

# Changing relative dimensions
# Positions relative to cryostat initialise
POSITIONS_FROM_CRYOSTAT = {"detector": 0.0, "holder": 0.0, "wrap": 0.0}
POSITION_SOURCE_FROM_CRYOSTAT_PHI = 0.0
POSITION_SOURCE_FROM_CRYOSTAT_R = 0.0
POSITION_SOURCE_FROM_CRYOSTAT_X = 0.0
POSITION_SOURCE_FROM_CRYOSTAT_Y = -0.0
POSITION_SOURCE_FROM_CRYOSTAT_Z = 200.0


def update_cryostat_dims(ged_meta_dict):
    POSITIONS_FROM_CRYOSTAT["detector"] = ged_meta_dict["hades"]["dimensions"]["detector"]["position"]
    POSITIONS_FROM_CRYOSTAT["holder"] = ged_meta_dict["hades"]["dimensions"]["holder"]["position"]
    POSITIONS_FROM_CRYOSTAT["wrap"] = ged_meta_dict["hades"]["dimensions"]["wrap"]["position"]
